development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: noreply.valentinas@gmail.com
  :password: riosdenim
  :enable_starttls_auto: true

production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: noreply.valentinas@gmail.com
  :password: riosdenim
  :enable_starttls_auto: true